version: '3.6'

networks:
  default:
    name: www-network

services:
  laravel9:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-php81-nginx:latest
    container_name: laravel9
    ports:
      - 1009:80
    restart: unless-stopped
    volumes:
      - ./application/:/var/www
    # - ./logs/nginx:/var/log/nginx
    # - ./server/php.ini-production:/etc/php81/php.ini
    # - ./server/nginx.conf:/etc/nginx/nginx.conf
    # - ./server/nginx-laravel.conf:/etc/nginx/modules
    networks:
      - default
